# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 08:28
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PopupContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('language', models.CharField(choices=[('de', 'De'), ('en', 'En'), ('fr', 'Fr'), ('it', 'It'), ('es', 'Es')], max_length=10, verbose_name='Language')),
                ('text', models.TextField(default='', verbose_name='Text')),
                ('button_label', models.CharField(blank=True, default='', max_length=150, verbose_name='Button label')),
            ],
            options={
                'ordering': ['language', '-id'],
                'verbose_name': 'Popup Content',
                'verbose_name_plural': 'Popup Content',
            },
        ),
        migrations.CreateModel(
            name='PopupLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('link_type', models.CharField(blank=True, choices=[('', '---'), ('link_cms_page', 'Seite'), ('link_url', 'URL')], default='', max_length=30, verbose_name='Link type')),
                ('link_url', models.URLField(blank=True, default='', max_length=255, verbose_name='URL')),
                ('link_cms_page', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tac_popuplink_set', to='cms.Page', verbose_name='Page')),
            ],
        ),
    ]
