# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupcontent',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site'),
        ),
    ]
