# Generated by Django 2.1.11 on 2019-08-23 11:24

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0002_popupcontent_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popuplink',
            name='link_cms_page',
            field=cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tac_popuplink_set', to='cms.Page', verbose_name='Page'),
        ),
    ]
