# Generated by Django 3.2.4 on 2021-06-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0003_auto_20190823_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupcontent',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch')], max_length=10, verbose_name='Language'),
        ),
    ]
