# Generated by Django 2.2.24 on 2021-06-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0005_alter_popupcontent_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopupLink',
        ),
    ]
